version: '3.8'

services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-password
      POSTGRES_DB: meters
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - consumption

volumes:
  pgdata:

networks:
  consumption:
    driver: bridge
